### ISSUE TITLE
`ari-examples/bridge-dial/example.py` what are the arguments to pass and how?

### ISSUE THREAD

**Issue by SonnyRajagopalan** [asterisk/ari-examples#10]
I am working with the examples, specifically `ari-examples/bridge-dial/example.py` and when I run it and dial an extension, I get the error 

     Error: PJSIP/1101-00000002 didn't provide any arguments!

Could you tell me how to provide the arguments to the Stasis application? I think it is the endpoint (the bridge number), but I am not sure how to provide it. The `extensions.conf` in the same directory did not indicate how to do this. Any help is appreciated.

Thanks!

**Comment by matt-jordan** [comment]
You need to provide the name of the endpoint you want to dial, e.g.,:

```
[default]

exten => 1000,1,NoOp()
 same =>      n,Stasis(bridge-move,inbound,PJSIP/bob)
 same =>      n,Hangup()
```

This example - and the dialplan needed to run it - is documented here:
https://wiki.asterisk.org/wiki/display/AST/ARI+and+Bridges%3A+Bridge+Operations
