### ISSUE TITLE
Not able to fire up on_dtmf_received on application

### ISSUE THREAD

**Issue by SonnyRajagopalan** [asterisk/ari-examples#11]
I have a stasis application registered in the dialplan like so:

```
exten => 6001,1,Stasis(bridge-dial-plus-dtmf-reaping,inbound,PJSIP/sonny)
exten => 6002,1,Stasis(bridge-dial-plus-dtmf-reaping,inbound,PJSIP/somebodyelse)
```

In the application that registers `bridge-dial-plus-dtmf-reaping`, I do everything in `ari-examples/bridge-dial/example.py`, but after `channel.answer()`, I do:

```
channel.on_event('ChannelDtmfReceived', on_dtmf_received)
```

And I introduce a new function before `stasis_start_cb` like so:

```
def on_dtmf_received(channel, ev):
    """Our handler for DTMF"""

    print "on_dtmf_received"
    print "Channel %s entered %d" % (channel.json.get('name'), int(ev.get('digit')))
```

Now, unfortunately, when I call the number 6002 from 6001 in the correct context, I see `bridge-dial-plus-dtmf` picks up the call, connects me over a bridge to the callee (6001), but unfortunately, does not reap the DTMF (does not print the lines in the function `on_dtmf_received`). What am I missing here? In fact, it is quite clear that the function is not being reached. How do I correctly register for DTMF listening? I have followed the core in `ari-examples/channel-aa/channel-aa.py` and excerpted out only the parts that I need (I do not need a menu to tell me to press numbers).

Any help is greatly appreciated. Thanks!

**Comment by samuelg** [comment]
Try creating the bridge as type 'mixing,dtmf_events' instead of 'mixing'. You can get more information on the create action [here](https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+Bridges+REST+API#Asterisk13BridgesRESTAPI-create).

**Comment by SonnyRajagopalan** [comment]
I tried the mixing,dtmf_events and that seems to have worked. I will post updates if I see any other issue. Thanks.
